// <auto-generated />
using BlazorEcommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230717100645_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorEcommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Octa-core (1x2.7 GHz Cortex-A78 & 3x2.4 GHz Cortex-A78 & 4x1.8 GHz Cortex-A55)",
                            ImageURL = "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce3-5g.jpg",
                            Price = 600m,
                            Title = "Nord CE3"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The OnePlus Nord 3 is finally here! It's been over two years since Nord 2 hit the shelves and it seems the wait was worth it. The third Nord brings a flagship-grade Fluid AMOLED, the top-of-the-line Dimensity 9000 5G chip, and an improved primary camera with a high-end Sony IMX890 sensor.",
                            ImageURL = "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-3r.jpg",
                            Price = 450m,
                            Title = "Nord 3"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Nord N30 5G is the latest entry in the Nord N line but is far from an unfamiliar device. The Nord N30 5G is actually the US device name for the OnePlus Nord CE 3 Lite - an identical device meant for Europe and Asia that we've already reviewed. Digging a bit deeper, it is not hard to spot the similarities between the Nord N30 5G and the Realme 10 Pro.",
                            ImageURL = "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-n30-5g.jpg",
                            Price = 299m,
                            Title = "Nord N30"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mediatek MT6983 Dimensity 9000 (4 nm)",
                            ImageURL = "https://fdn2.gsmarena.com/vv/bigpic/oneplus-ace-2v.jpg",
                            Price = 200m,
                            Title = "Ace 2V"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
